/**
 * MapFileName table from Unit1.pas — all known *c.rel filenames with labels.
 *
 * NOTE: The index in this array is NOT the PSO floor/area slot ID.
 * The correct file for a given floor is set by the quest script bytecode.
 * This list exists so the user can manually pick the right file in the canvas.
 */
export interface MapEntry {
  file: string;   // *c.rel filename
  label: string;  // human-readable area name
}

export const MAP_ENTRIES: readonly MapEntry[] = [
  // ── Episode 1 ──────────────────────────────────────────────────────────
  { file: 'map_city00_00c.rel',          label: 'Pioneer II' },
  { file: 'map_forest01c.rel',           label: 'Forest 1' },
  { file: 'map_forest02c.rel',           label: 'Forest 2' },
  { file: 'map_cave01_00c.rel',          label: 'Caves 1 – Room 00' },
  { file: 'map_cave01_01c.rel',          label: 'Caves 1 – Room 01' },
  { file: 'map_cave01_02c.rel',          label: 'Caves 1 – Room 02' },
  { file: 'map_cave01_03c.rel',          label: 'Caves 1 – Room 03' },
  { file: 'map_cave01_04c.rel',          label: 'Caves 1 – Room 04' },
  { file: 'map_cave01_05c.rel',          label: 'Caves 1 – Room 05' },
  { file: 'map_cave02_00c.rel',          label: 'Caves 2 – Room 00' },
  { file: 'map_cave02_01c.rel',          label: 'Caves 2 – Room 01' },
  { file: 'map_cave02_02c.rel',          label: 'Caves 2 – Room 02' },
  { file: 'map_cave02_03c.rel',          label: 'Caves 2 – Room 03' },
  { file: 'map_cave02_04c.rel',          label: 'Caves 2 – Room 04' },
  { file: 'map_cave02_05c.rel',          label: 'Caves 2 – Room 05' },
  { file: 'map_cave03_00c.rel',          label: 'Caves 3 – Room 00' },
  { file: 'map_cave03_01c.rel',          label: 'Caves 3 – Room 01' },
  { file: 'map_cave03_02c.rel',          label: 'Caves 3 – Room 02' },
  { file: 'map_cave03_03c.rel',          label: 'Caves 3 – Room 03' },
  { file: 'map_cave03_04c.rel',          label: 'Caves 3 – Room 04' },
  { file: 'map_cave03_05c.rel',          label: 'Caves 3 – Room 05' },
  { file: 'map_machine01_00c.rel',       label: 'Mines 1 – Room 00' },
  { file: 'map_machine01_01c.rel',       label: 'Mines 1 – Room 01' },
  { file: 'map_machine01_02c.rel',       label: 'Mines 1 – Room 02' },
  { file: 'map_machine01_03c.rel',       label: 'Mines 1 – Room 03' },
  { file: 'map_machine01_04c.rel',       label: 'Mines 1 – Room 04' },
  { file: 'map_machine01_05c.rel',       label: 'Mines 1 – Room 05' },
  { file: 'map_machine02_00c.rel',       label: 'Mines 2 – Room 00' },
  { file: 'map_machine02_01c.rel',       label: 'Mines 2 – Room 01' },
  { file: 'map_machine02_02c.rel',       label: 'Mines 2 – Room 02' },
  { file: 'map_machine02_03c.rel',       label: 'Mines 2 – Room 03' },
  { file: 'map_machine02_04c.rel',       label: 'Mines 2 – Room 04' },
  { file: 'map_machine02_05c.rel',       label: 'Mines 2 – Room 05' },
  { file: 'map_ancient01_00c.rel',       label: 'Ruins 1 – Room 00' },
  { file: 'map_ancient01_01c.rel',       label: 'Ruins 1 – Room 01' },
  { file: 'map_ancient01_02c.rel',       label: 'Ruins 1 – Room 02' },
  { file: 'map_ancient01_03c.rel',       label: 'Ruins 1 – Room 03' },
  { file: 'map_ancient01_04c.rel',       label: 'Ruins 1 – Room 04' },
  { file: 'map_ancient02_00c.rel',       label: 'Ruins 2 – Room 00' },
  { file: 'map_ancient02_01c.rel',       label: 'Ruins 2 – Room 01' },
  { file: 'map_ancient02_02c.rel',       label: 'Ruins 2 – Room 02' },
  { file: 'map_ancient02_03c.rel',       label: 'Ruins 2 – Room 03' },
  { file: 'map_ancient02_04c.rel',       label: 'Ruins 2 – Room 04' },
  { file: 'map_ancient03_00c.rel',       label: 'Ruins 3 – Room 00' },
  { file: 'map_ancient03_01c.rel',       label: 'Ruins 3 – Room 01' },
  { file: 'map_ancient03_02c.rel',       label: 'Ruins 3 – Room 02' },
  { file: 'map_ancient03_03c.rel',       label: 'Ruins 3 – Room 03' },
  { file: 'map_ancient03_04c.rel',       label: 'Ruins 3 – Room 04' },
  { file: 'map_boss01c.rel',             label: 'Dragon (Boss)' },
  { file: 'map_boss02c.rel',             label: 'De Rol Le (Boss)' },
  { file: 'map_boss03c.rel',             label: 'Vol Opt (Boss)' },
  { file: 'map_darkfalz00c.rel',         label: 'Dark Falz (Boss)' },
  { file: 'map_lobby_00c.rel',           label: 'Lobby' },
  { file: 'map_lobby_green_be00c.rel',   label: 'Lobby (Green Battle)' },
  { file: 'map_lobby_red_be00c.rel',     label: 'Lobby (Red Battle)' },
  { file: 'map_lobby_yellow_be00c.rel',  label: 'Lobby (Yellow Battle)' },
  { file: 'map_soccer11c.rel',           label: 'Battle Soccer' },
  { file: 'map_vs01_00c.rel',            label: 'VS – Room 00' },
  { file: 'map_vs01_01c.rel',            label: 'VS – Room 01' },
  { file: 'map_vs01_02c.rel',            label: 'VS – Room 02' },
  { file: 'map_vs02_00c.rel',            label: 'VS2 – Room 00' },
  { file: 'map_vs02_01c.rel',            label: 'VS2 – Room 01' },
  { file: 'map_vs02_02c.rel',            label: 'VS2 – Room 02' },
  // ── Episode 2 ──────────────────────────────────────────────────────────
  { file: 'map_labo00_00c.rel',          label: 'Ep2 – Lab' },
  { file: 'map_ruins01_00c.rel',         label: 'Ep2 – VR Temple Alpha – Room 00' },
  { file: 'map_ruins01_01c.rel',         label: 'Ep2 – VR Temple Alpha – Room 01' },
  { file: 'map_ruins01_02c.rel',         label: 'Ep2 – VR Temple Alpha – Room 02' },
  { file: 'map_ruins02_00c.rel',         label: 'Ep2 – VR Temple Beta – Room 00' },
  { file: 'map_ruins02_01c.rel',         label: 'Ep2 – VR Temple Beta – Room 01' },
  { file: 'map_ruins02_02c.rel',         label: 'Ep2 – VR Temple Beta – Room 02' },
  { file: 'map_space01_00c.rel',         label: 'Ep2 – VR Spaceship Alpha – Room 00' },
  { file: 'map_space01_01c.rel',         label: 'Ep2 – VR Spaceship Alpha – Room 01' },
  { file: 'map_space01_02c.rel',         label: 'Ep2 – VR Spaceship Alpha – Room 02' },
  { file: 'map_space02_00c.rel',         label: 'Ep2 – VR Spaceship Beta – Room 00' },
  { file: 'map_space02_01c.rel',         label: 'Ep2 – VR Spaceship Beta – Room 01' },
  { file: 'map_space02_02c.rel',         label: 'Ep2 – VR Spaceship Beta – Room 02' },
  { file: 'map_jungle01_00c.rel',        label: 'Ep2 – CCA – Room 00' },
  { file: 'map_jungle02_00c.rel',        label: 'Ep2 – CCA – Room 01' },
  { file: 'map_jungle03_00c.rel',        label: 'Ep2 – CCA – Room 02' },
  { file: 'map_jungle04_00c.rel',        label: 'Ep2 – CCA – Room 03' },
  { file: 'map_jungle04_01c.rel',        label: 'Ep2 – CCA – Room 04' },
  { file: 'map_jungle04_02c.rel',        label: 'Ep2 – CCA – Room 05' },
  { file: 'map_jungle05_00c.rel',        label: 'Ep2 – CCA – Room 06' },
  { file: 'map_seabed01_00c.rel',        label: 'Ep2 – Seabed Upper – Room 00' },
  { file: 'map_seabed01_01c.rel',        label: 'Ep2 – Seabed Upper – Room 01' },
  { file: 'map_seabed01_02c.rel',        label: 'Ep2 – Seabed Upper – Room 02' },
  { file: 'map_seabed02_00c.rel',        label: 'Ep2 – Seabed Lower – Room 00' },
  { file: 'map_seabed02_01c.rel',        label: 'Ep2 – Seabed Lower – Room 01' },
  { file: 'map_seabed02_02c.rel',        label: 'Ep2 – Seabed Lower – Room 02' },
  { file: 'map_boss05c.rel',             label: 'Ep2 – Gal Gryphon (Boss)' },
  { file: 'map_boss06c.rel',             label: 'Ep2 – Olga Flow (Boss)' },
  { file: 'map_boss07c.rel',             label: 'Ep2 – Barba Ray (Boss)' },
  { file: 'map_boss08c.rel',             label: 'Ep2 – Gol Dragon (Boss)' },
  { file: 'map_jungle06_00c.rel',        label: 'Ep2 – Jungle North' },
  { file: 'map_jungle07_00c.rel',        label: 'Ep2 – Jungle South – Room 00' },
  { file: 'map_jungle07_01c.rel',        label: 'Ep2 – Jungle South – Room 01' },
  { file: 'map_jungle07_02c.rel',        label: 'Ep2 – Jungle South – Room 02' },
  { file: 'map_jungle07_03c.rel',        label: 'Ep2 – Jungle South – Room 03' },
  { file: 'map_jungle07_04c.rel',        label: 'Ep2 – Jungle South – Room 04' },
  // ── Episode 4 ──────────────────────────────────────────────────────────
  { file: 'map_wilds01_00c.rel',         label: 'Ep4 – Wilds – Room 00' },
  { file: 'map_wilds01_01c.rel',         label: 'Ep4 – Wilds – Room 01' },
  { file: 'map_wilds01_02c.rel',         label: 'Ep4 – Wilds – Room 02' },
  { file: 'map_wilds01_03c.rel',         label: 'Ep4 – Wilds – Room 03' },
  { file: 'map_crater01_00c.rel',        label: 'Ep4 – Crater' },
  { file: 'map_desert01_00c.rel',        label: 'Ep4 – Desert 1 – Room 00' },
  { file: 'map_desert01_01c.rel',        label: 'Ep4 – Desert 1 – Room 01' },
  { file: 'map_desert01_02c.rel',        label: 'Ep4 – Desert 1 – Room 02' },
  { file: 'map_desert02_00c.rel',        label: 'Ep4 – Desert 2' },
  { file: 'map_desert03_00c.rel',        label: 'Ep4 – Desert 3 – Room 00' },
  { file: 'map_desert03_01c.rel',        label: 'Ep4 – Desert 3 – Room 01' },
  { file: 'map_desert03_02c.rel',        label: 'Ep4 – Desert 3 – Room 02' },
  { file: 'map_boss09_00c.rel',          label: 'Ep4 – Saint-Milion (Boss)' },
  { file: 'map_city02_00c.rel',          label: 'Ep4 – Pioneer II (EP4)' },
  // ── Test / misc ────────────────────────────────────────────────────────
  { file: 'map_test01_00c.rel',          label: 'Test Room' },
];

/** Derive the *n.rel filename from the *c.rel filename */
export function toNRelName(cRelName: string): string {
  return cRelName.replace(/c\.rel$/, 'n.rel');
}
